Compile clojurescript during build

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -143,11 +143,22 @@ fi
 echo "       Running: $BUILD_COMMAND"
 
 cd $BUILD_DIR
+
+# Run build command
 PATH=.lein/bin:$PATH JVM_OPTS="-Xmx600m" \
   LEIN_JVM_OPTS="-Xmx400m -Duser.home=$BUILD_DIR" \
   $BUILD_COMMAND 2>&1 | sed -u 's/^/       /'
 if [ "${PIPESTATUS[*]}" != "0 0" ]; then
   echo " !     Failed to build."
+  exit 1
+fi
+
+# Compile ClojureScript
+PATH=.lein/bin:$PATH JVM_OPTS="-Xmx600m" \
+  LEIN_JVM_OPTS="-Xmx400m -Duser.home=$BUILD_DIR" \
+  lein cljsbuild once production
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+  echo " !     Failed to compile ClojureScript. Exiting."
   exit 1
 fi
 
