Fix for inability to run lein

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -156,7 +156,15 @@ fi
 # Compile ClojureScript
 PATH=.lein/bin:$PATH JVM_OPTS="-Xmx600m" \
   LEIN_JVM_OPTS="-Xmx400m -Duser.home=$BUILD_DIR" \
-  lein cljsbuild clean && lein cljsbuild once production
+  lein cljsbuild clean
+if [ $? != 0 ]; then
+  echo " !     cljsbuild clean failed. Exiting."
+  exit 1
+fi
+
+PATH=.lein/bin:$PATH JVM_OPTS="-Xmx600m" \
+  LEIN_JVM_OPTS="-Xmx400m -Duser.home=$BUILD_DIR" \
+  lein cljsbuild once production
 if [ $? != 0 ]; then
   echo " !     Failed to compile ClojureScript. Exiting."
   exit 1
